name: CI/CD Pipeline for OWASP Juice Shop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-juice-shop:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Pull Docker image
      - name: Pull OWASP Juice Shop Image
        run: docker pull bkimminich/juice-shop

      # Step 3: Run Juice Shop container
      - name: Deploy OWASP Juice Shop
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

        
  sast-codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript

  sca-snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Snyk Dependency Scan
        uses: snyk/actions/node@v1
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  dast-owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Juice Shop for Testing
        run: docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:3000'

      - name: Cleanup
        run: docker stop juice-shop && docker rm juice-shop

  vulnerability-reporting:
    runs-on: ubuntu-latest
    steps:
      - name: Send Results to DefectDojo
        env:
          DEFECT_DOJO_API_KEY: ${{ secrets.DEFECT_DOJO_API_KEY }}
        run: |
          curl -X POST \
          -H "Authorization: Token $DEFECT_DOJO_API_KEY" \
          -H "Content-Type: application/json" \
          -d @results.json \
          "http://defectdojo.example.com/api/v2/import-scan/"


